serp:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------

  box_cilinder_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: box_cilinder_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  box_cilinder_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: box_cilinder_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  box_cilinder_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: box_cilinder_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  box_cilinder_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: box_cilinder_joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}

  box_cilinder_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: box_cilinder_joint5
    pid: {p: 100.0, i: 0.01, d: 10.0}

  box_cilinder_joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: box_cilinder_joint6
    pid: {p: 100.0, i: 0.01, d: 10.0}

  box_cilinder_joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: box_cilinder_joint7
    pid: {p: 100.0, i: 0.01, d: 10.0}

  box_cilinder_joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: box_cilinder_joint8
    pid: {p: 100.0, i: 0.01, d: 10.0}

  box_cilinder_joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: box_cilinder_joint9
    pid: {p: 100.0, i: 0.01, d: 10.0}




  
